import { IDBProduct } from "@/types/IProduct";

const products: any[] = [
  {
    id: "1",
    name: "Apple Juice",
    unitPrice: 3.5,
    shelfLife: "12 months",
    brand: "JuicyFruit",
  },
  {
    id: "2",
    name: "Banana Chips",
    unitPrice: 2.0,
    shelfLife: "6 months",
    brand: "Snacky",
  },
  {
    id: "3",
    name: "Organic Honey",
    unitPrice: 8.0,
    shelfLife: "24 months",
    brand: "SweetBee",
  },
  {
    id: "4",
    name: "Almond Milk",
    unitPrice: 4.2,
    shelfLife: "10 days",
    brand: "Nutty",
  },
  {
    id: "5",
    name: "Dark Chocolate",
    unitPrice: 5.5,
    shelfLife: "18 months",
    brand: "CocoaDelight",
  },
  {
    id: "6",
    name: "Peanut Butter",
    unitPrice: 6.0,
    shelfLife: "15 months",
    brand: "NutSpread",
  },
  {
    id: "7",
    name: "Olive Oil",
    unitPrice: 10.5,
    shelfLife: "36 months",
    brand: "Olivetto",
  },
  {
    id: "8",
    name: "Green Tea",
    unitPrice: 3.0,
    shelfLife: "12 months",
    brand: "TeaTime",
  },
  {
    id: "9",
    name: "Protein Bars",
    unitPrice: 2.5,
    shelfLife: "9 months",
    brand: "FitBites",
  },
  {
    id: "10",
    name: "Granola",
    unitPrice: 3.8,
    shelfLife: "8 months",
    brand: "Crunchy",
  },
  {
    id: "11",
    name: "Rice Cakes",
    unitPrice: 1.5,
    shelfLife: "6 months",
    brand: "SnackOn",
  },
  {
    id: "12",
    name: "Tomato Sauce",
    unitPrice: 3.2,
    shelfLife: "12 months",
    brand: "Saucy",
  },
  {
    id: "13",
    name: "Canned Beans",
    unitPrice: 2.8,
    shelfLife: "24 months",
    brand: "Beanify",
  },
  {
    id: "14",
    name: "Instant Coffee",
    unitPrice: 4.0,
    shelfLife: "18 months",
    brand: "QuickBrew",
  },
  {
    id: "15",
    name: "Pasta",
    unitPrice: 2.0,
    shelfLife: "18 months",
    brand: "Pastamia",
  },
  {
    id: "16",
    name: "Cereal",
    unitPrice: 3.7,
    shelfLife: "12 months",
    brand: "MorningCrunch",
  },
  {
    id: "17",
    name: "Coconut Water",
    unitPrice: 2.5,
    shelfLife: "9 months",
    brand: "TropicalSip",
  },
  {
    id: "18",
    name: "Cheese",
    unitPrice: 7.5,
    shelfLife: "30 days",
    brand: "DairyDelight",
  },
  {
    id: "19",
    name: "Frozen Peas",
    unitPrice: 2.2,
    shelfLife: "12 months",
    brand: "FrostFresh",
  },
  {
    id: "20",
    name: "Herbal Shampoo",
    unitPrice: 6.0,
    shelfLife: "36 months",
    brand: "NatureCare",
  },
];

export default products;
